# Site settings
title: CSS Complexity Calculator
email: "http://www.gregboggs.com"
description: "Scan your website's CSS to determine how complex your theme is. The better your code, the less complex your CSS."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
