# Site settings
title: CSS Complexity Calculator
email: "http://www.gregboggs.com"
description: "This scanner will run the numbers on your CSS complexity. A lower score is better."
baseurl: ""
url: "http://css.gregboggs.com"
github: "Greg-Boggs/css-complexity"
twitter: "gregory_boggs"

# Build settings
markdown: kramdown
permalink: pretty
